### ISSUE TITLE
patch for fast-safe-stringify dependency

### ISSUE THREAD

**Issue by zolaemil** [hapijs/good-squeeze#21]
This issue https://github.com/davidmarkclements/fast-safe-stringify/issues/4 makes the latest release unsafe to use. Would you consider releasing a patch `4.0.1` with the updated dependency?

**Comment by Marsup** [comment]
It's the reasonable thing to do.

**Comment by arb** [comment]
Yes.

**Comment by zolaemil** [comment]
Not sure what's the best way to submit a PR, since this needs to branch from https://github.com/hapijs/good-squeeze/releases/tag/v4.0.0 but I pushed it to my fork: https://github.com/zolaemil/good-squeeze/tree/patch/fast-safe-stringify-dep

**Comment by arb** [comment]
Oh geeze, you want to back port this dependency update! Got you. Didn't put that together yet.

What version of fast-safe-stringify should we use?

**Comment by zolaemil** [comment]
Releasing 5.0.0 would also be fine I guess. Though backporting it would mean everyone using 4.x.x could receive it.

**Comment by Marsup** [comment]
Why backport ? Upgrade to 5 is nothing.

**Comment by arb** [comment]
Yeah in general I don't patch old versions. That's pretty typical in the hapi ecosystem. I'll take a PR updating version 5 to use the suggested version.

**Comment by glesperance** [comment]
Hey guys, just restarting this thread as I think it's very important we get PR #26 merged with master and pushed to NPM as soon as possible

[Fast Safe Stringify](https://github.com/davidmarkclements/fast-safe-stringify) v1.1.11 fixes important issues regarding objects that provide a `toJSON` method.

Moreover, the way it breaks makes it pretty hard to diagnose the problem down to good-squeeze/fast-safe-stringify.

For the record, we found this issue was causing critical crashes on our servers whenever we tried to output Sequelize objects to the log via Good.
